### ISSUE TITLE
Incorrect algorithm in blogpost

### ISSUE THREAD

**Issue by jcranch** [Rgetar/rgetar.github.io#9]
Hello! I can't find an email address for you. I'm James Cranch at the University of Sheffield; you can find an email address for me quickly by searching the web.

I think the [description](https://googology.fandom.com/wiki/User_blog:Rgetar/Comparison_of_ordinals_expressed_through_extended_Veblen_function) you have given of comparing values of the extended Veblen function is incorrect.

For example, suppose you compare φ(1,0,0,0) and φ(1,0,0). In step 1, you find that 1 (on the left) is bigger than 0 (on the right). In step 2, you find that the remaining terms 0, 0, and 0 are all less than φ(1,0,0), so you report that φ(1,0,0,0) is smaller than φ(1,0,0). Oops!

I think you should be comparing the remaining terms of the ordinal which had the **smaller** value with the ordinal with the **larger** value, not the other way around, right?

**Comment by Rgetar** [comment]
Hello! It looks like you are right. I corrected the blogpost. Do you think the algorithm is now correct now?

**Comment by jcranch** [comment]
Thanks - I believe it now!
